
# - Imported targets for Boost port.
# Generated by CMake @CMAKE_VERSION@

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)


#----------------------------------------------------------------
# CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target "Boost::boost" for header only libs.
add_library(Boost::boost INTERFACE IMPORTED)
set_target_properties(Boost::boost PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${Boost_INCLUDE_DIRS}"
)

# Create imported targets "Boost::<component>" for compiled libs.
set(Boost_INSTALLED_COMPONENTS @Boost_COMPONENTS@)
foreach(_boost_comp ${Boost_INSTALLED_COMPONENTS})
  add_library(Boost::${_boost_comp} @Boost_LINK_MODEL@ IMPORTED)
  set_target_properties(Boost::${_boost_comp} PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES "${Boost_INCLUDE_DIR}"
  )
endforeach()

if(CMAKE_VERSION VERSION_LESS 2.8.12)
  message(FATAL_ERROR
    "This file relies on consumers using CMake 2.8.12 or greater."
  )
endif()

# Load information for each installed configuration.
get_filename_component(_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
file(GLOB CONFIG_FILES
  "${_DIR}/BoostTargets-@Boost_LINK_MODEL_TAG@-@Boost_THREAD_MODEL_TAG@-*.cmake"
)
foreach(f ${CONFIG_FILES})
  include(${f})
endforeach()

# Loop over all imported files and verify that they actually exist.
foreach(target ${_IMPORT_CHECK_TARGETS} )
  foreach(file ${_IMPORT_CHECK_FILES_FOR_${target}} )
    if(NOT EXISTS "${file}" )
      message(FATAL_ERROR
        ### Begin of string.
"
The imported target \"${target}\" references the file
   \"${file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
"
        ### End of string.
      )  # message(FATAL_ERROR)
    endif()
  endforeach()
  unset(_IMPORT_CHECK_FILES_FOR_${target})
endforeach()
unset(_IMPORT_CHECK_TARGETS)

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
